on:
  push:
  pull_request:
    types: [opened, edited]
name: "js-tests"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-2022
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Rust Nightly
        run: |
          rustup default nightly
          rustup update

      - name: Rustup Target - Linux
        if: runner.os == 'Linux'
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Rustup Target - Mac
        if: runner.os == 'macOS'
        run: rustup component add rust-src --toolchain nightly-x86_64-apple-darwin

      - name: Setup WABT
        uses: chiefbiiko/setup-wabt@1.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test --scope='!@vlcn.io/py-correctness'
