on:
  push:
  pull_request:
    types: [opened, edited]
name: "js-tests"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-2022
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Rust Nightly
        run: |
          rustup default nightly
          rustup update

      - name: Rustup Target - Linux
        if: runner.os == 'Linux'
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Rustup Target - Mac
        if: runner.os == 'macOS'
        run: rustup component add rust-src --toolchain nightly-x86_64-apple-darwin

      - name: Setup WABT - Liunx
        if: runner.os == 'Linux'
        run: |
          curl -L https://github.com/WebAssembly/wabt/releases/download/1.0.32/wabt-1.0.32-ubuntu.tar.gz | tar -xz -C ~
          echo "$HOME/wabt-1.0.32/bin" >> $GITHUB_PATH

      - name: Setup WABT - Mac
        if: runner.os == 'macOS'
        run: |
          curl -L https://github.com/WebAssembly/wabt/releases/download/1.0.32/wabt-1.0.32-macos-12.tar.gz | tar -xz -C ~
          echo "$HOME/wabt-1.0.32/bin" >> $GITHUB_PATH

      - name: Setup WABT - Windows
        if: runner.os == 'Windows'
        run: |
          curl https://github.com/WebAssembly/wabt/releases/download/1.0.32/wabt-1.0.32-windows.tar.gz > ~/wabt.tar.gz
          ls ~
          cd ~ && tar -zxf wabt.tar.gz
          echo "$HOME/wabt-1.0.32/bin" >> $GITHUB_PATH

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test --scope='!@vlcn.io/py-correctness'
