on:
  push:
name: "rs-tests"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-2022
          - os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./
          load-mode: strict

      - name: Rust Nightly
        run: |
          rustup default nightly
          rustup update

      - name: Windows rust toolchain
        if: runner.os == 'Windows'
        run: |
          find . -name rust-toolchain -exec echo rm {} \;
          rustup component add rust-src --toolchain nightly-2023-06-17-x86_64-pc-windows-gnu
          rustup default nightly-2023-06-17-x86_64-pc-windows-gnu

      - name: Test Fractindex
        run: |
          cd core/rs/fractindex-core
          cargo test --features=loadable_extension

      - name: Integration Tests
        run: |
          cd core/rs/integration-check
          cargo test
